baseURL = 'https://docs.excelscheduler.field3.systems'
languageCode = 'en-us'
title = 'Excel Class Scheduler'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'


[params]
BookTheme = 'auto'
BookSection = 'docs'
BookRepo = 'https://github.com/bmayfi3ld/excel-scheduler'
