baseURL = 'https://example.com'
languageCode = 'en-us'
title = 'Excel Class Scheduler'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'


[params]
BookTheme = 'auto'
BookSection = 'docs'
